spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/rflow_products
    username: postgres
    password: DATABASE_PASSWORD

  sql:
    init:
      mode: never

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8083
